version: "3"
services:
  db:
    image: mysql:5.7
    command: mysqld --sql_mode=
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: railsdatabase
    ports:
      - "3306:3306"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sampleApp
    ports:
      - "3000:3000"
    depends_on:
      - db
